<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260315154624 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE contact_fournisseur (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(60) NOT NULL, prenom VARCHAR(60) DEFAULT NULL, fonction VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, tel_contact VARCHAR(30) DEFAULT NULL, fournisseur_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5832758C670C757F ON contact_fournisseur (fournisseur_id)');
        $this->addSql('ALTER TABLE contact_fournisseur ADD CONSTRAINT FK_5832758C670C757F FOREIGN KEY (fournisseur_id) REFERENCES fournisseur (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE contact_fournisseur DROP CONSTRAINT FK_5832758C670C757F');
        $this->addSql('DROP TABLE contact_fournisseur');
    }
}
