<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260315213323 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE demande_echantillon (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_demande DATE NOT NULL, etat VARCHAR(30) DEFAULT \'EN_COURS\' NOT NULL, delai_livraison DATE DEFAULT NULL, fournisseur_id INT NOT NULL, mp_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8D43C493670C757F ON demande_echantillon (fournisseur_id)');
        $this->addSql('CREATE INDEX IDX_8D43C49355BFF85F ON demande_echantillon (mp_id)');
        $this->addSql('ALTER TABLE demande_echantillon ADD CONSTRAINT FK_8D43C493670C757F FOREIGN KEY (fournisseur_id) REFERENCES fournisseur (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE demande_echantillon ADD CONSTRAINT FK_8D43C49355BFF85F FOREIGN KEY (mp_id) REFERENCES mat_premiere (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE lot ADD demande_echantillon_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE lot ADD CONSTRAINT FK_B81291BD957C174 FOREIGN KEY (demande_echantillon_id) REFERENCES demande_echantillon (id)');
        $this->addSql('CREATE INDEX IDX_B81291BD957C174 ON lot (demande_echantillon_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE demande_echantillon DROP CONSTRAINT FK_8D43C493670C757F');
        $this->addSql('ALTER TABLE demande_echantillon DROP CONSTRAINT FK_8D43C49355BFF85F');
        $this->addSql('DROP TABLE demande_echantillon');
        $this->addSql('ALTER TABLE lot DROP CONSTRAINT FK_B81291BD957C174');
        $this->addSql('DROP INDEX IDX_B81291BD957C174');
        $this->addSql('ALTER TABLE lot DROP demande_echantillon_id');
    }
}
