<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260314233610 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE mat_premiere (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom_mp VARCHAR(200) NOT NULL, inci VARCHAR(200) DEFAULT NULL, noi VARCHAR(60) DEFAULT NULL, categorie VARCHAR(80) DEFAULT NULL, fonction VARCHAR(255) DEFAULT NULL, cosmos VARCHAR(10) DEFAULT NULL, PRIMARY KEY (id))');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE mat_premiere');
    }
}
