<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260331170524 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE alerte (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type_alerte VARCHAR(40) NOT NULL, etat_alerte VARCHAR(30) DEFAULT \'ACTIVE\' NOT NULL, date_alerte TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, message TEXT DEFAULT NULL, lot_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3AE753AA8CBA5F7 ON alerte (lot_id)');
        $this->addSql('CREATE TABLE contact_fournisseur (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(60) NOT NULL, prenom VARCHAR(60) DEFAULT NULL, fonction VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, tel_contact VARCHAR(30) DEFAULT NULL, fournisseur_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5832758C670C757F ON contact_fournisseur (fournisseur_id)');
        $this->addSql('CREATE TABLE demande_echantillon (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_demande DATE NOT NULL, etat VARCHAR(30) DEFAULT \'EN_COURS\' NOT NULL, delai_livraison DATE DEFAULT NULL, fournisseur_id INT NOT NULL, mp_id INT NOT NULL, alerte_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8D43C493670C757F ON demande_echantillon (fournisseur_id)');
        $this->addSql('CREATE INDEX IDX_8D43C49355BFF85F ON demande_echantillon (mp_id)');
        $this->addSql('CREATE INDEX IDX_8D43C4932C9BA629 ON demande_echantillon (alerte_id)');
        $this->addSql('CREATE TABLE distribue (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, distribution_id INT NOT NULL, mp_id INT NOT NULL, contact_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_84EEF6FB6EB6DDB5 ON distribue (distribution_id)');
        $this->addSql('CREATE INDEX IDX_84EEF6FB55BFF85F ON distribue (mp_id)');
        $this->addSql('CREATE INDEX IDX_84EEF6FBE7A1254A ON distribue (contact_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_dist_mp ON distribue (distribution_id, mp_id)');
        $this->addSql('CREATE TABLE distribution (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom_marque VARCHAR(200) NOT NULL, fournisseur_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A4483781670C757F ON distribution (fournisseur_id)');
        $this->addSql('CREATE TABLE fournir (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, prix NUMERIC(10, 2) DEFAULT NULL, moq NUMERIC(10, 2) DEFAULT NULL, mat_prem_id INT NOT NULL, fournisseur_id INT NOT NULL, distribution_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_34D13A5244B7C10E ON fournir (mat_prem_id)');
        $this->addSql('CREATE INDEX IDX_34D13A52670C757F ON fournir (fournisseur_id)');
        $this->addSql('CREATE INDEX IDX_34D13A526EB6DDB5 ON fournir (distribution_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_prix_mp_four_dist ON fournir (mat_prem_id, fournisseur_id, distribution_id)');
        $this->addSql('CREATE TABLE fournisseur (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom_entr VARCHAR(200) NOT NULL, adresse VARCHAR(200) DEFAULT NULL, email_gen VARCHAR(200) DEFAULT NULL, tel_fourni VARCHAR(30) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE lot (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, num_lot VARCHAR(60) NOT NULL, date_arrivee DATE DEFAULT NULL, ddm DATE DEFAULT NULL, qt_initiale NUMERIC(12, 2) NOT NULL, qt_restante NUMERIC(12, 2) DEFAULT NULL, date_maj TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, qt_min NUMERIC(12, 2) DEFAULT NULL, etat VARCHAR(50) DEFAULT \'OK\' NOT NULL, mp_id INT NOT NULL, demande_echantillon_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B81291B55BFF85F ON lot (mp_id)');
        $this->addSql('CREATE INDEX IDX_B81291BD957C174 ON lot (demande_echantillon_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_num_lot ON lot (num_lot)');
        $this->addSql('CREATE TABLE mat_premiere (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom_mp VARCHAR(200) NOT NULL, inci VARCHAR(200) DEFAULT NULL, noi VARCHAR(60) DEFAULT NULL, categorie VARCHAR(80) DEFAULT NULL, fonction VARCHAR(255) DEFAULT NULL, cosmos VARCHAR(10) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE alerte ADD CONSTRAINT FK_3AE753AA8CBA5F7 FOREIGN KEY (lot_id) REFERENCES lot (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE contact_fournisseur ADD CONSTRAINT FK_5832758C670C757F FOREIGN KEY (fournisseur_id) REFERENCES fournisseur (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE demande_echantillon ADD CONSTRAINT FK_8D43C493670C757F FOREIGN KEY (fournisseur_id) REFERENCES fournisseur (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE demande_echantillon ADD CONSTRAINT FK_8D43C49355BFF85F FOREIGN KEY (mp_id) REFERENCES mat_premiere (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE demande_echantillon ADD CONSTRAINT FK_8D43C4932C9BA629 FOREIGN KEY (alerte_id) REFERENCES alerte (id)');
        $this->addSql('ALTER TABLE distribue ADD CONSTRAINT FK_84EEF6FB6EB6DDB5 FOREIGN KEY (distribution_id) REFERENCES distribution (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE distribue ADD CONSTRAINT FK_84EEF6FB55BFF85F FOREIGN KEY (mp_id) REFERENCES mat_premiere (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE distribue ADD CONSTRAINT FK_84EEF6FBE7A1254A FOREIGN KEY (contact_id) REFERENCES contact_fournisseur (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE distribution ADD CONSTRAINT FK_A4483781670C757F FOREIGN KEY (fournisseur_id) REFERENCES fournisseur (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE fournir ADD CONSTRAINT FK_34D13A5244B7C10E FOREIGN KEY (mat_prem_id) REFERENCES mat_premiere (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE fournir ADD CONSTRAINT FK_34D13A52670C757F FOREIGN KEY (fournisseur_id) REFERENCES fournisseur (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE fournir ADD CONSTRAINT FK_34D13A526EB6DDB5 FOREIGN KEY (distribution_id) REFERENCES distribution (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE lot ADD CONSTRAINT FK_B81291B55BFF85F FOREIGN KEY (mp_id) REFERENCES mat_premiere (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE lot ADD CONSTRAINT FK_B81291BD957C174 FOREIGN KEY (demande_echantillon_id) REFERENCES demande_echantillon (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE alerte DROP CONSTRAINT FK_3AE753AA8CBA5F7');
        $this->addSql('ALTER TABLE contact_fournisseur DROP CONSTRAINT FK_5832758C670C757F');
        $this->addSql('ALTER TABLE demande_echantillon DROP CONSTRAINT FK_8D43C493670C757F');
        $this->addSql('ALTER TABLE demande_echantillon DROP CONSTRAINT FK_8D43C49355BFF85F');
        $this->addSql('ALTER TABLE demande_echantillon DROP CONSTRAINT FK_8D43C4932C9BA629');
        $this->addSql('ALTER TABLE distribue DROP CONSTRAINT FK_84EEF6FB6EB6DDB5');
        $this->addSql('ALTER TABLE distribue DROP CONSTRAINT FK_84EEF6FB55BFF85F');
        $this->addSql('ALTER TABLE distribue DROP CONSTRAINT FK_84EEF6FBE7A1254A');
        $this->addSql('ALTER TABLE distribution DROP CONSTRAINT FK_A4483781670C757F');
        $this->addSql('ALTER TABLE fournir DROP CONSTRAINT FK_34D13A5244B7C10E');
        $this->addSql('ALTER TABLE fournir DROP CONSTRAINT FK_34D13A52670C757F');
        $this->addSql('ALTER TABLE fournir DROP CONSTRAINT FK_34D13A526EB6DDB5');
        $this->addSql('ALTER TABLE lot DROP CONSTRAINT FK_B81291B55BFF85F');
        $this->addSql('ALTER TABLE lot DROP CONSTRAINT FK_B81291BD957C174');
        $this->addSql('DROP TABLE alerte');
        $this->addSql('DROP TABLE contact_fournisseur');
        $this->addSql('DROP TABLE demande_echantillon');
        $this->addSql('DROP TABLE distribue');
        $this->addSql('DROP TABLE distribution');
        $this->addSql('DROP TABLE fournir');
        $this->addSql('DROP TABLE fournisseur');
        $this->addSql('DROP TABLE lot');
        $this->addSql('DROP TABLE mat_premiere');
    }
}
