<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260315172224 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE distribue (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, distribution_id INT NOT NULL, mp_id INT NOT NULL, contact_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_84EEF6FB6EB6DDB5 ON distribue (distribution_id)');
        $this->addSql('CREATE INDEX IDX_84EEF6FB55BFF85F ON distribue (mp_id)');
        $this->addSql('CREATE INDEX IDX_84EEF6FBE7A1254A ON distribue (contact_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_dist_mp ON distribue (distribution_id, mp_id)');
        $this->addSql('ALTER TABLE distribue ADD CONSTRAINT FK_84EEF6FB6EB6DDB5 FOREIGN KEY (distribution_id) REFERENCES distribution (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE distribue ADD CONSTRAINT FK_84EEF6FB55BFF85F FOREIGN KEY (mp_id) REFERENCES mat_premiere (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE distribue ADD CONSTRAINT FK_84EEF6FBE7A1254A FOREIGN KEY (contact_id) REFERENCES contact_fournisseur (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE distribue DROP CONSTRAINT FK_84EEF6FB6EB6DDB5');
        $this->addSql('ALTER TABLE distribue DROP CONSTRAINT FK_84EEF6FB55BFF85F');
        $this->addSql('ALTER TABLE distribue DROP CONSTRAINT FK_84EEF6FBE7A1254A');
        $this->addSql('DROP TABLE distribue');
    }
}
