<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260424131835 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE document (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom_file VARCHAR(200) NOT NULL, type VARCHAR(50) DEFAULT NULL, date_upload TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE doc_lot (document_id INT NOT NULL, lot_id INT NOT NULL, PRIMARY KEY (document_id, lot_id))');
        $this->addSql('CREATE INDEX IDX_A20BE867C33F7837 ON doc_lot (document_id)');
        $this->addSql('CREATE INDEX IDX_A20BE867A8CBA5F7 ON doc_lot (lot_id)');
        $this->addSql('CREATE TABLE doc_mp (document_id INT NOT NULL, mat_premiere_id INT NOT NULL, PRIMARY KEY (document_id, mat_premiere_id))');
        $this->addSql('CREATE INDEX IDX_F7E059C5C33F7837 ON doc_mp (document_id)');
        $this->addSql('CREATE INDEX IDX_F7E059C54DEAC08C ON doc_mp (mat_premiere_id)');
        $this->addSql('CREATE TABLE doc_four (document_id INT NOT NULL, fournisseur_id INT NOT NULL, PRIMARY KEY (document_id, fournisseur_id))');
        $this->addSql('CREATE INDEX IDX_C9DBD1ABC33F7837 ON doc_four (document_id)');
        $this->addSql('CREATE INDEX IDX_C9DBD1AB670C757F ON doc_four (fournisseur_id)');
        $this->addSql('CREATE TABLE email (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, txt TEXT DEFAULT NULL, date_envoie TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, sujet VARCHAR(200) DEFAULT NULL, demande_echantillon_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E7927C74D957C174 ON email (demande_echantillon_id)');
        $this->addSql('ALTER TABLE doc_lot ADD CONSTRAINT FK_A20BE867C33F7837 FOREIGN KEY (document_id) REFERENCES document (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE doc_lot ADD CONSTRAINT FK_A20BE867A8CBA5F7 FOREIGN KEY (lot_id) REFERENCES lot (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE doc_mp ADD CONSTRAINT FK_F7E059C5C33F7837 FOREIGN KEY (document_id) REFERENCES document (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE doc_mp ADD CONSTRAINT FK_F7E059C54DEAC08C FOREIGN KEY (mat_premiere_id) REFERENCES mat_premiere (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE doc_four ADD CONSTRAINT FK_C9DBD1ABC33F7837 FOREIGN KEY (document_id) REFERENCES document (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE doc_four ADD CONSTRAINT FK_C9DBD1AB670C757F FOREIGN KEY (fournisseur_id) REFERENCES fournisseur (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE email ADD CONSTRAINT FK_E7927C74D957C174 FOREIGN KEY (demande_echantillon_id) REFERENCES demande_echantillon (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE doc_lot DROP CONSTRAINT FK_A20BE867C33F7837');
        $this->addSql('ALTER TABLE doc_lot DROP CONSTRAINT FK_A20BE867A8CBA5F7');
        $this->addSql('ALTER TABLE doc_mp DROP CONSTRAINT FK_F7E059C5C33F7837');
        $this->addSql('ALTER TABLE doc_mp DROP CONSTRAINT FK_F7E059C54DEAC08C');
        $this->addSql('ALTER TABLE doc_four DROP CONSTRAINT FK_C9DBD1ABC33F7837');
        $this->addSql('ALTER TABLE doc_four DROP CONSTRAINT FK_C9DBD1AB670C757F');
        $this->addSql('ALTER TABLE email DROP CONSTRAINT FK_E7927C74D957C174');
        $this->addSql('DROP TABLE document');
        $this->addSql('DROP TABLE doc_lot');
        $this->addSql('DROP TABLE doc_mp');
        $this->addSql('DROP TABLE doc_four');
        $this->addSql('DROP TABLE email');
    }
}
