<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260315192625 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE lot (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, num_lot VARCHAR(60) NOT NULL, date_arrivee DATE DEFAULT NULL, ddm DATE DEFAULT NULL, qt_initiale NUMERIC(12, 2) NOT NULL, qt_restante NUMERIC(12, 2) DEFAULT NULL, date_maj TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, qt_min NUMERIC(12, 2) DEFAULT NULL, etat VARCHAR(50) DEFAULT \'OK\' NOT NULL, mp_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B81291B55BFF85F ON lot (mp_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_num_lot ON lot (num_lot)');
        $this->addSql('ALTER TABLE lot ADD CONSTRAINT FK_B81291B55BFF85F FOREIGN KEY (mp_id) REFERENCES mat_premiere (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE lot DROP CONSTRAINT FK_B81291B55BFF85F');
        $this->addSql('DROP TABLE lot');
    }
}
