<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260315230450 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE alerte (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type_alerte VARCHAR(40) NOT NULL, etat_alerte VARCHAR(30) DEFAULT \'ACTIVE\' NOT NULL, date_alerte TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, message TEXT DEFAULT NULL, lot_id INT NOT NULL, demande_echantillon_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3AE753AA8CBA5F7 ON alerte (lot_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3AE753AD957C174 ON alerte (demande_echantillon_id)');
        $this->addSql('ALTER TABLE alerte ADD CONSTRAINT FK_3AE753AA8CBA5F7 FOREIGN KEY (lot_id) REFERENCES lot (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE alerte ADD CONSTRAINT FK_3AE753AD957C174 FOREIGN KEY (demande_echantillon_id) REFERENCES demande_echantillon (id)');
        $this->addSql('ALTER TABLE demande_echantillon ADD alerte_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE demande_echantillon ADD CONSTRAINT FK_8D43C4932C9BA629 FOREIGN KEY (alerte_id) REFERENCES alerte (id)');
        $this->addSql('CREATE INDEX IDX_8D43C4932C9BA629 ON demande_echantillon (alerte_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE alerte DROP CONSTRAINT FK_3AE753AA8CBA5F7');
        $this->addSql('ALTER TABLE alerte DROP CONSTRAINT FK_3AE753AD957C174');
        $this->addSql('DROP TABLE alerte');
        $this->addSql('ALTER TABLE demande_echantillon DROP CONSTRAINT FK_8D43C4932C9BA629');
        $this->addSql('DROP INDEX IDX_8D43C4932C9BA629');
        $this->addSql('ALTER TABLE demande_echantillon DROP alerte_id');
    }
}
