<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260315164825 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE fournir (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, prix NUMERIC(10, 2) DEFAULT NULL, moq NUMERIC(10, 2) DEFAULT NULL, mat_prem_id INT NOT NULL, fournisseur_id INT NOT NULL, distribution_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_34D13A5244B7C10E ON fournir (mat_prem_id)');
        $this->addSql('CREATE INDEX IDX_34D13A52670C757F ON fournir (fournisseur_id)');
        $this->addSql('CREATE INDEX IDX_34D13A526EB6DDB5 ON fournir (distribution_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_prix_mp_four_dist ON fournir (mat_prem_id, fournisseur_id, distribution_id)');
        $this->addSql('ALTER TABLE fournir ADD CONSTRAINT FK_34D13A5244B7C10E FOREIGN KEY (mat_prem_id) REFERENCES mat_premiere (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE fournir ADD CONSTRAINT FK_34D13A52670C757F FOREIGN KEY (fournisseur_id) REFERENCES fournisseur (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE fournir ADD CONSTRAINT FK_34D13A526EB6DDB5 FOREIGN KEY (distribution_id) REFERENCES distribution (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE fournir DROP CONSTRAINT FK_34D13A5244B7C10E');
        $this->addSql('ALTER TABLE fournir DROP CONSTRAINT FK_34D13A52670C757F');
        $this->addSql('ALTER TABLE fournir DROP CONSTRAINT FK_34D13A526EB6DDB5');
        $this->addSql('DROP TABLE fournir');
    }
}
