services:
  fw2:
    build:
      context: .
      dockerfile: Dockerfile
      no_cache: true
      args:
        USERNAME: meriem
        UID: 1000
        EMAIL: meriem.ould-taleb@univ-orleans.fr
        NAME: "meriem ould taleb"

    container_name: LaboWelab

    # 👉 Lancement automatique du serveur Symfony dans Docker
    command: php -S 0.0.0.0:8000 -t public

    tty: true
    stdin_open: true

    # 👉 On monte directement le backend Symfony
    volumes:
      - ./workspace/weLab_backend:/var/www/html

    ports:
      - "8011:8000"   # Backend Symfony
      - "8021:4200"   # Frontend Angular

    environment:
      PHP_IDE_CONFIG: serverName=contacts
      PS1: "[ $$(whoami) | $$(pwd) ] "
      DATABASE_URL: "postgresql://labo_user:labo_password1234@database:5432/labo_stock?serverVersion=15&charset=utf8"

    depends_on:
      - database

    networks:
      - welab_network

  # Base de données PostgreSQL
  database:
    image: postgres:15-alpine
    container_name: welab-database
    environment:
      POSTGRES_DB: labo_stock
      POSTGRES_USER: labo_user
      POSTGRES_PASSWORD: labo_password1234
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - welab_network

volumes:
  postgres_data:

networks:
  welab_network:
    driver: bridge
