# config/routes.yaml
controllers:
    resource: ../src/Controller/
    type: attribute

api_login_check:
    path: /api/login_check
    # controller: lexik_jwt_authentication.handler.authentication_success
    methods: ['POST']

api_doc:
    path: /api/docs
    controller: api_platform.action.documentation